coverage_service: cobertura_xml
scheme: AdventOfCode2025
output_directory: ./slather-report
workspace: AdventOfCode2022.xcodeproj/project.xcworkspace
xcodeproj: AdventOfCode2022.xcodeproj
ignore:
    - ../**/*/Xcode*
    - ../core/*

