trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'macos-12'
  demands: xcode
  
variables:
  sdk: 'iphoneos'
  projectPath: 'AdventOfCode2022.xcodeproj'
  workspacePath: 'AdventOfCode2022.xcworkspace'
  scheme: 'AdventOfCode2022'
  configuration: 'Debug'
  
steps:
  - task: CocoaPods@0
    displayName: 'pod install'
  - task: Xcode@5
    displayName: "XCode Build"
    inputs:
      actions: 'build'
      scheme: '$(scheme)'
      configuration: '$(configuration)'
      xcWorkspacePath: 'AdventOfCode2022.xcworkspace'
      xcodeVersion: 'default'
      publishJUnitResults: true
      
  - task: Xcode@5
    displayName: 'Running tests'
    inputs:
     actions: 'test'
     sdk: 'iphonesimulator'
     scheme: '$(scheme)'
     configuration: '$(configuration)'
     xcWorkspacePath: '$(workspacePath)'
     xcodeVersion: 'default'
     args: '-destination "platform=iOS Simulator,name=iPhone 14 Pro Max"'
      
  - script: gem install slather
    displayName: 'Install Slather'

  - script: slather
    displayName: 'Run slather'

  - task: PublishCodeCoverageResults@1
    inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/slather-report'
