trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'macos-12'
  demands: xcode
steps:
  - task: CocoaPods@0
    displayName: 'pod install'
  - task: Xcode@5
    displayName: "XCode Build"
    inputs:
      actions: 'build'
      scheme: 'AdventOfCode2022'
      sdk: 'iphoneos'
      configuration: 'Debug'
      xcWorkspacePath: 'AdventOfCode2022.xcworkspace'
      xcodeVersion: 'default'
      publishJUnitResults: true
      
  - script: gem install slather
    displayName: 'Install Slather'

  - script: fastlane run slather
    displayName: 'Run slather'

  - task: PublishCodeCoverageResults@1
    inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/slather-report'
