trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'macos-12'
  demands: xcode
steps:
  - task: Xcode@5
    displayName: "XCode Build"
    inputs:
      actions: 'build'
      scheme: ''
      sdk: 'iphoneos'
      configuration: 'Debug'
      xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
      xcodeVersion: 'default'
      publishJUnitResults: true
      
  - script: gem install slather
    displayName: 'Install Slather'

  - script: slather
    displayName: 'Run slather'

  - task: PublishCodeCoverageResults@1
    inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/slather-report'
