trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'macos-12'
  demands: xcode
  
variables:
  sdk: 'iphoneos'
  projectPath: 'AdventOfCode2022.xcodeproj'
  workspacePath: 'AdventOfCode2022.xcworkspace'
  scheme: 'AdventOfCode2022'
  configuration: 'Debug'
  coveragePath: '$(agent.buildDirectory)/coverage/'
  artifactName: 'ArtifactName'
  
steps:
  - task: CocoaPods@0
    displayName: 'pod install'
  - task: Xcode@5
    displayName: "XCode Build"
    inputs:
      actions: 'build'
      scheme: '$(scheme)'
      sdk: '$(sdk)'
      configuration: 'Debug'
      xcWorkspacePath: 'AdventOfCode2022.xcworkspace'
      xcodeVersion: 'default'
      publishJUnitResults: true
      
  - task: Xcode@5
    displayName: 'Run XCTest/XCUITest'
    inputs:
     actions: 'test'
     sdk: '$(sdk)'
     scheme: '$(scheme)'
     configuration: '$(configuration)'
     xcWorkspacePath: '$(workspacePath)'
     xcodeVersion: 'default'
      
  - script: gem install slather
    displayName: 'Install Slather'

  - script: slather coverage -x --scheme AdventOfCode2022 --workspace AdventOfCode2022.xcworkspace --output-directory $(coveragepath) $(projectPath)
    displayName: 'Run slather'

  - task: PublishCodeCoverageResults@1
    inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/slather-report'
